# Generated by Django 3.0 on 2021-07-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='previews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_media', to='multimedia.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='images',
            field=models.ManyToManyField(blank=True, to='multimedia.Image'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='tag',
            field=models.ManyToManyField(blank=True, to='multimedia.MultimediaTags'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='videos',
            field=models.ManyToManyField(blank=True, to='multimedia.Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
