# Generated by Django 3.0 on 2021-09-18 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_auto_20210728_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimediaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('[^\\w\\-]', inverse_match=True, message='Spaces and punctuation (except "-" and "_") are not allowed.')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MultimediaTags',
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='tag',
            field=models.ManyToManyField(blank=True, to='multimedia.MultimediaTag'),
        ),
    ]
