# Generated by Django 3.0 on 2022-11-05 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0008_auto_20221105_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='multiple_images',
            field=models.FileField(blank=True, help_text='Upload Multiple Images', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='preview',
            field=models.ForeignKey(blank=True, help_text='Pick the Preview Image', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_media', to='multimedia.Image'),
        ),
    ]
