# Generated by Django 3.0 on 2022-11-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0010_multimedia_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(help_text='Enables screen readers to read the information about the image', max_length=100),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='multiple_images',
            field=models.FileField(blank=True, help_text='Upload Zip File of Multiple Images', null=True, upload_to=''),
        ),
    ]
