#!/usr/bin/env python

import sys


def no_push_master():
    """Prevent pushing local master to remote"""
    red = '\033[91m'
    reset = '\033[0m'

    for line in sys.stdin:
        print(line)
        if not line.split():
            continue
        localname, _, remotename, _ = line.split()

    #-- Checks if master or develop branch is being deleted --#
    #-- Keep this above the general push to master code for more specific message --#
    if localname == '(delete)' and remotename in ['refs/heads/master', 'refs/heads/develop']:
        print()
        print(red + "pre-push hook: You should not delete the master or develop branches in remote." + reset)
        print(red + " "*15 + "This is a dangerous action." + reset)
        print()
        sys.exit(1)

    #-- Checks if any branch is being pushed to remote master --#
    try:
        if remotename == 'refs/heads/master':
            print()
            print(red + "pre-push hook: You cannot push to remote master." + reset)
            print(red + "If you really want to do this, use --no-verify to bypass this pre-commit hook." + reset)
            print()
            sys.exit(1)
    except UnboundLocalError as e:
        if 'remotename' in e.args[0]:
            sys.exit(0)
        else:
            sys.exit(1)


if __name__ == '__main__':
    no_push_master()
    sys.exit(0)
