# Generated by Django 4.2.7 on 2023-11-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_auto_20210502_0227"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
