FROM python:3.9-slim-bookworm as base-python

# Set timezone
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get -y install \
        tzdata \
        postgresql-server-dev-all \
        build-essential \
        git
RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

# Install Stuff
WORKDIR /app
COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

# Multi Stage Builds
FROM base-python AS prod
COPY . .

FROM base-python as dev
