kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: deploy
  commands:
  - cd /home/kisa/kisaweb
  - git checkout master
  - sh deactivatescript.sh
  - git pull https://github.com/kisawebkaist/kisaweb
  - . venv/bin/activate
  - yes | pip install -r requirements.txt
  - python web/manage.py migrate
  - python web/manage.py collectstatic --noinput
  - sh activatescript.sh

- name: fallback
  commands:
  - cd /home/kisa/kisaweb
  - sh activatescript.sh
  when:
    status:
    - failure

- name: apache2-status
  commands:
  - systemctl status apache2
  when:
    status:
    - failure

- name: drone-status
  commands:
  - systemctl status drone
  when:
    status:
    - failure

trigger:
  branch:
  - master
  event:
  - push
