kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: apache2-status
  commands:
  - systemctl status apache2

- name: drone-status
  commands:
  - systemctl status drone

- name: check-scripts
  commands:
  - ls
  - cat scripts/reactivatescript.sh
  - sh scripts/reactivatescript.sh
  - source scripts/reactivatescript.sh

trigger:
  branch:
  - feat/60/ci
  event:
  - push
  - pull_request
