kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - systemctl status apache2
  - systemctl status drone
  - cat scripts/reactivatescript.sh

trigger:
  branch:
  - feat/60/ci
  event:
  - push
  - pull_request
