kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

# clone:
#   disable: true

steps:
- name: apache2-status
  commands:
  - systemctl status apache2

- name: drone-status
  commands:
  - systemctl status drone

- name: deploy
  commands:
  - cd /home/kisa/kisaweb
  - git status
  - git checkout master
  - sh deactivatescript.sh
  - git pull https://github.com/kisawebkaist/kisaweb
  - sh activatescript.sh

# - name: check-scripts
#   commands:
#   - ls
#   - cat scripts/reactivatescript.sh
#   - sh scripts/reactivatescript.sh
#   - source scripts/reactivatescript.sh

trigger:
  branch:
  - feat/60/ci
  event:
  - push
  - pull_request
