version: '3.3'
services:
  db:
    image: postgres:14-bookworm
    secrets:
      - db_name
      - db_user
      - db_password
    environment:
      - POSTGRES_DB=/run/secrets/db_name
      - POSTGRES_USER=/run/secrets/db_user
      - POSTGRES_PASSWORD=/run/secrets/db_password
    volumes:
      - ./data/db:/var/lib/postgresql/data
  backend:
    build:
      dockerfile: dockerfile.backend
      context: ./backend
      target: prod
    command: gunicorn web.wsgi -b 0.0.0.0:8000 --workers=10
    secrets:
      - db_name
      - db_user
      - db_password
      - secret_key
      - public_key
      - private_key
      - sso_secret
    environment:
      - PRODUCTION=true
      - SECRET_KEY=/run/secrets/secret_key
      - DB_USER=/run/secrets/db_user
      - DB_NAME=/run/secrets/db_name
      - DB_PASSWORD=/run/secrets/db_password
      - DB_PORT=5432
      - DB_HOST=db
      - KSSO_SECRET_KEY=/run/secrets/sso_secret
      - KSSO_CLIENT_ID=KISA
      - KSSO_LOGIN_URL=https://iam2.kaist.ac.kr
      - KSSO_LOGOUT_URL=https://iam2.kaist.ac.kr
      - ALLOWED_HOSTS=kisa.kaist.ac.kr
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:81,https://kisa.kaist.ac.kr:10001
  frontend:
    build:
      dockerfile: dockerfile.frontend
      context: ./frontend
      target: prod
      args:
        - REACT_APP_API_PUBLIC_KEY=/run/secrets/public_key
        - REACT_APP_API_ENDPOINT=https://kisa.kaist.ac.kr:10002/api/
    command: serve -s build -l tcp://0.0.0.0:3000
  nginx:
    build:
      dockerfile: dockerfile
      context: ./install/nginx
      target: prod
    ports:
      - 10001:443
      - 10002:8081
    environment:
      - BACKEND_ENDPOINT=backend
      - BACKEND_PORT=8000
      - BACKEND_LISTEN_PORT=8081
      - FRONTEND_ENDPOINT=frontend
      - FRONTEND_PORT=3000
      - FRONTEND_HTTP_PORT=80
      - FRONTEND_HTTPS_PORT=443
      - NGINX_HOST=kisa.kaist.ac.kr
secrets:
  db_name:
    file: ../secrets/db_name.txt
  db_user:
    file: ../secrets/db_user.txt
  db_password:
    file: ../secrets/db_password.txt
  secret_key:
    file: ../secrets/secret_key.txt
  public_key:
    file: ../secrets/public_key.txt
  private_key:
    file: ../secrets/private_key.txt
  sso_secret:
    file: ../secrets/sso_secret.txt
