version: '3.3'
services:
  db:
    image: postgres:14-bookworm
    secrets:
      - db_name
      - db_user
      - db_password
    environment:
      - POSTGRES_DB_FILE=/run/secrets/db_name
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - ./data/db:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.backend
      target: prod
    command: gunicorn web.wsgi -b unix:/tmp/django/django.sock --workers=10 --reload
    depends_on:
      db:
        condition: service_started
        restart: true
    volumes:
      - ./backend/src:/app
      - /tmp/django:/tmp/django
    secrets:
      - django_secrets_dotenv
    environment:
      - ALLOWED_HOSTS=kisa.kaist.ac.kr
      - API_ROOT=/api/
      - CORS_ALLOW_CREDENTIALS=1
      - CORS_ALLOWED_ORIGINS=https://localhost:81,https://kisa.kaist.ac.kr:8080
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=0
      - SMTP_SERVER=example.com
      - SMTP_USERNAME=admin
      - SMTP_PASSWORD=password123
      - DOTENV_FILE=/run/secrets/django_secrets_dotenv
secrets:
  db_name:
    file: ${HOME}/.secrets/db_name.txt
  db_user:
    file: ${HOME}/.secrets/db_user.txt
  db_password:
    file: ${HOME}/.secrets/db_password.txt
  django_secrets_dotenv:
    file: ${HOME}/.secrets/django_secrets_dotenv.txt