version: '3.3'
services:
  db:
    build:
      dockerfile: dockerfile.postgres
      context: ./install
    environment:
      - POSTGRES_DB=/run/secrets/db_name
      - POSTGRES_USER=/run/secrets/db_user
      - POSTGRES_PASSWORD=/run/secrets/db_password
  backend:
    build:
      dockerfile: dockerfile.backend
      context: ./backend
      target: prod
    environment:
      - SECRET_KEY=/run/secrets/secret_key
      - PRIVATE_KEY=/run/secrets/private_key
      - PUBLIC_KEY=/run/secrets/public_key
      - DB_USER=/run/secrets/db_user
      - DB_NAME=/run/secrets/db_name
      - DB_PASSWORD=/run/secrets/db_password
      - DB_PORT=5432
      - DB_HOST=db
  frontend:
    build:
      dockerfile: dockerfile.frontend
      context: ./frontend
      target: prod
      args:
        - REACT_APP_API_PUBLIC_KEY=/run/secrets/public_key
        - REACT_APP_API_ENDPOINT=https://kisa.kaist.ac.kr
  nginx:
    build:
      dockerfile: dockerfile
      context: ./install/nginx
      target: prod
    ports:
      - 80:80
      - 443:443
      - 8000:8081
    environment:
      - BACKEND_ENDPOINT=backend
      - BACKEND_PORT=8000
      - BACKEND_LISTEN_PORT=8081
      - FRONTEND_ENDPOINT=frontend
      - FRONTEND_PORT=3000
      - FRONTEND_HTTP_PORT=80
      - FRONTEND_HTTPS_PORT=443
      - NGINX_HOST=kisa.kaist.ac.kr
