version: '3.3'
services:
  db:
    image: postgres:14-bookworm
    environment:
      - POSTGRES_DB=kisaweb
      - POSTGRES_USER=kisaweb
      - POSTGRES_PASSWORD=ilovekisa
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    build:
      dockerfile: dockerfile.backend
      context: ./backend
      target: dev
    command: gunicorn web.wsgi -b unix:/tmp/django/django.sock --workers=10 --reload
    volumes:
      - ./backend/src:/app
      - ./backend/media:/media
      - shared_django_tmp:/tmp/django
    depends_on:
      - db
      - nginx
    environment:
      - ALLOWED_HOSTS=localhost
      - API_ROOT=/api/
      - CORS_ALLOW_CREDENTIALS=1
      - CORS_ALLOWED_ORIGINS=https://localhost:81,https://kisa.kaist.ac.kr:8080
      - DB_NAME=kisaweb
      - DB_USER=kisaweb
      - DB_PASSWORD=ilovekisa
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=1
      - KSSO_CLIENT_SECRET=GAGHS4AIC6SNHUY3Y36AQEZVFAMQXFPDTWZJOPYDPFMU72BRBKRRDXJMLSNSYM6A
      - SECRET_KEY=dVtGYO19KLsw8lY3kuAU3Qn2kSw6j1BqNrwOVMa92qWgu949jN
      - SMTP_SERVER=example.com
      - SMTP_USERNAME=admin
      - SMTP_PASSWORD=password123
  nginx:
    build:
      dockerfile: dockerfile
      context: ./install/nginx
      target: dev
    volumes:
      - static_content:/www/html/kisa.kaist.ac.kr:ro
      - shared_django_tmp:/tmp/django
      - ./install/nginx/templates:/etc/nginx/templates:ro
    ports:
      - 81:8081
      - 8001:8080
      - 3001:8081
    depends_on:
      - frontend
      - backend
    environment:
      - BACKEND_ENDPOINT=backend
      - BACKEND_PORT=8000
      - BACKEND_LISTEN_PORT=8080
      - FRONTEND_ENDPOINT=frontend
      - FRONTEND_PORT=3000
      - FRONTEND_LISTEN_PORT=8081
      - NGINX_HOST=localhost
volumes:
  static_content:
    driver_opts:
      type: none
      device: ${PWD}/build
      o: bind
  shared_django_tmp:
    driver_opts:
      type: none
      device: /tmp/django
      o: bind