site_name: KISA Web Documentation

# Repository
repo_name: kisawebkaist/kisaweb
repo_url: https://github.com/kisawebkaist/kisaweb
edit_uri: ""


theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  language: en
  
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.expand
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
  
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: ⚓︎