# Generated by Django 4.2.11 on 2025-07-30 09:29

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-event_start_datetime"]},
        ),
        migrations.RenameField(
            model_name="event",
            old_name="image",
            new_name="poster",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="registration_end_datetime",
            new_name="reg_end_datetime",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="registration_start_datetime",
            new_name="reg_start_datetime",
        ),
        migrations.RemoveField(
            model_name="event",
            name="current_occupancy",
        ),
        migrations.RemoveField(
            model_name="event",
            name="descr_truncate_num",
        ),
        migrations.RemoveField(
            model_name="event",
            name="has_registration_form",
        ),
        migrations.RemoveField(
            model_name="event",
            name="image_height",
        ),
        migrations.RemoveField(
            model_name="event",
            name="image_width",
        ),
        migrations.RemoveField(
            model_name="event",
            name="is_link",
        ),
        migrations.RemoveField(
            model_name="event",
            name="link",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.RemoveField(
            model_name="event",
            name="registration_form_src",
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=core.utils.DraftJSEditorField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="max_occupancy",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
