# Generated by Django 3.0 on 2023-02-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KISA_Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('joined_season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], default='Spring', max_length=6)),
                ('joined_year', models.IntegerField()),
                ('separated_season', models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], help_text='if the alumni only worked for one season please leave this part empty.', max_length=6, null=True)),
                ('separated_year', models.IntegerField(blank=True, help_text='if the alumni only worked for one season please leave this part empty.', null=True)),
                ('current_contact', models.URLField(blank=True, help_text='Current contact of the Alumni. Be sure to ask the alumni for permission to post it here.', null=True)),
                ('worked_positions', models.ManyToManyField(to='alumni.KISA_Positions')),
            ],
        ),
    ]
