# Generated by Django 3.0 on 2023-06-08 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KISA_Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'KISA_Positions',
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('joined_season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], default='Spring', max_length=6)),
                ('joined_year', models.IntegerField(default=2004, validators=[django.core.validators.MinValueValidator(2004), django.core.validators.MaxValueValidator(2023)])),
                ('separated_season', models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], help_text='If the alumni only worked for one season please leave this part empty.', max_length=6, null=True)),
                ('separated_year', models.IntegerField(default=2023, help_text='If the alumni only worked for one season please enter the same year as joined year.', validators=[django.core.validators.MinValueValidator(2004), django.core.validators.MaxValueValidator(2023)])),
                ('current_contact', models.URLField(blank=True, help_text='Current contact of the Alumni. Be sure to ask the alumni for permission to post it.', null=True)),
                ('worked_positions', models.ManyToManyField(to='alumni.KISA_Position')),
            ],
            options={
                'verbose_name_plural': 'Alumnus',
            },
        ),
    ]
