# Generated by Django 3.0 on 2024-03-23 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='joined_year',
            field=models.IntegerField(default=2004, validators=[django.core.validators.MinValueValidator(2004), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='separated_year',
            field=models.IntegerField(default=2024, help_text='If the alumni only worked for one season please enter the same year as joined year.', validators=[django.core.validators.MinValueValidator(2004), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
