# Generated by Django 4.2.7 on 2023-11-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0002_auto_20220907_0004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlshortener",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="urlvisit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="urlvisitor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
