# Generated by Django 4.2.11 on 2025-07-30 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alumni", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumni",
            name="division",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="alumni",
            name="head_year",
            field=models.CharField(
                blank=True,
                help_text="Year of head position, e.g. 2022",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="alumni",
            name="picture",
            field=models.URLField(
                blank=True, help_text="URL to alumni picture", null=True
            ),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="joined_year",
            field=models.IntegerField(
                default=2004,
                validators=[
                    django.core.validators.MinValueValidator(2004),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="separated_year",
            field=models.IntegerField(
                default=2025,
                help_text="If the alumni only worked for one season please enter the same year as joined year.",
                validators=[
                    django.core.validators.MinValueValidator(2004),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
        ),
    ]
