# Generated by Django 4.2.10 on 2024-02-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KAISTProfile",
            fields=[
                ("kaist_uid", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "korean_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("full_name", models.CharField(blank=True, max_length=100, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sex", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "kaist_email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                (
                    "external_email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                ("employee_number", models.IntegerField(blank=True, null=True)),
                ("student_number", models.IntegerField(blank=True, null=True)),
                (
                    "bachelors_department_code",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "bachelors_department_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("campus", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "title_english",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "student_status_english",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "student_status_korean",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("degree_code", models.IntegerField(blank=True, null=True)),
                (
                    "degree_name_korean",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "degree_name_english",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "employee_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "student_admission_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("student_type_id", models.IntegerField(blank=True, null=True)),
                (
                    "student_type_class",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "student_category_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("student_enrollment_date", models.DateField(blank=True, null=True)),
                ("student_graduation_date", models.DateField(blank=True, null=True)),
                ("student_department_id", models.IntegerField(blank=True, null=True)),
                ("sso_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "student_department_name_english",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "student_department_name_korean",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_login", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="LoginError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
