# Generated by Django 3.0 on 2021-12-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_auto_20210313_0234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agreement',
        ),
    ]
