# Generated by Django 3.0 on 2022-01-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0004_auto_20211223_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
