# Generated by Django 4.2.10 on 2024-02-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinkCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_category",
                    models.CharField(blank=True, max_length=200, unique=True),
                ),
            ],
            options={
                "ordering": ("title_category",),
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField(unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("is_english", models.BooleanField(default=True)),
                ("requires_sso", models.BooleanField(default=True)),
                ("external_access", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        related_query_name="link",
                        to="important_links.linkcategory",
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
    ]
