# Generated by Django 4.2.10 on 2024-02-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("election", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="slug",
            field=models.SlugField(max_length=120),
        ),
    ]
