# Generated by Django 3.0 on 2022-01-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_election_results_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_open',
        ),
        migrations.AddField(
            model_name='election',
            name='is_open_public',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='is_open_staff',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
