# Generated by Django 3.0 on 2022-01-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20220110_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'permissions': [('see_election_results', 'Can view election results anytime'), ('preview_election', 'Can preview the election before it is published')]},
        ),
        migrations.RemoveField(
            model_name='election',
            name='is_open_staff',
        ),
    ]
