# Generated by Django 3.0 on 2022-01-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_auto_20220120_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='consider_debate_participation',
            new_name='show_debate_participation',
        ),
        migrations.AddField(
            model_name='election',
            name='general_vote_weight',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='kisa_no_debate_weight',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='kisa_yes_debate_weight',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='use_the_manual_weights',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
