# Generated by Django 3.0 on 2022-01-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_auto_20220120_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='general_vote_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='kisa_no_debate_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='kisa_yes_debate_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, null=True),
        ),
    ]
