# Generated by Django 3.0 on 2022-01-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_auto_20220120_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='kisa_in_debate_vote_explanation',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='kisa_vote_explanation',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='non_kisa_vote_explanation',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='weighted_vote_explanation',
            field=models.TextField(default='', null=True),
        ),
    ]
