# Generated by Django 3.0 on 2021-07-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20210710_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Student life', 'Student'), ('Academics', 'Academics'), ('Advices', 'Advices'), ('Nothing', 'Nothing')], default='nothing', max_length=20),
        ),
    ]
