# Generated by Django 3.0 on 2021-07-19 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_auto_20210719_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, choices=[('Student life', 'Student'), ('Academics', 'Academics'), ('Advices', 'Advices'), ('nothing', 'nothing')], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='faq.Category'),
        ),
    ]
