# Generated by Django 3.0 on 2021-07-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0007_auto_20210719_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Student life', 'Student'), ('Academics', 'Academics'), ('Advices', 'Advices'), ('nothing', 'nothing')], default='nothing', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
