# Generated by Django 3.0 on 2021-07-22 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0009_auto_20210719_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title_category',
            field=models.CharField(blank=True, choices=[('', '---'), ('Student life', 'Student'), ('Academics', 'Academics'), ('Advices', 'Advices'), ('nothing', 'nothing')], max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, choices=[('', '---'), ('Student life', 'Student'), ('Academics', 'Academics'), ('Advices', 'Advices'), ('nothing', 'nothing')], null=True, on_delete=django.db.models.deletion.CASCADE, to='faq.Category'),
        ),
    ]
