# Generated by Django 3.0 on 2021-07-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0010_auto_20210722_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title_category',
            new_name='tittle_category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
