# Generated by Django 3.0 on 2021-07-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0011_auto_20210722_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faq.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tittle_category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
