# Generated by Django 3.0 on 2021-07-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0012_auto_20210724_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tittle_category',
            new_name='title_category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='faq',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
