# Generated by Django 3.0 on 2021-09-15 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0015_auto_20210913_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='faq.Category'),
            preserve_default=False,
        ),
    ]
