# Generated by Django 3.0 on 2021-09-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0016_auto_20210915_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
