# Generated by Django 3.0 on 2022-01-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0017_auto_20210915_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='FAQCategory',
        ),
    ]
