# Generated by Django 3.0 on 2022-03-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('important_links', '0002_auto_20220118_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkcategory',
            options={'ordering': ('title_category',)},
        ),
        migrations.AlterField(
            model_name='linkcategory',
            name='title_category',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
