# Generated by Django 4.2.7 on 2023-11-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aboutus", "0002_auto_20231111_1044"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basecontent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="basemember",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
