# Generated by Django 3.0 on 2022-01-06 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('manifesto', tinymce.models.HTMLField()),
                ('speech_url', models.CharField(blank=True, max_length=512, null=True)),
                ('kisa_history', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='election/img')),
                ('date', models.DateField(auto_now_add=True)),
                ('embed_video_ratio', models.CharField(choices=[('21by9', '21by9'), ('16by9', '16by9'), ('4by3', '4by3'), ('1by1', '1by1')], default='16by9', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('intro_msg', tinymce.models.HTMLField()),
                ('instructions', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='election/img')),
                ('debate_url', models.CharField(blank=True, max_length=512, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('kisa_member_email_list', models.TextField(blank=True)),
                ('embed_video_ratio', models.CharField(choices=[('21by9', '21by9'), ('16by9', '16by9'), ('4by3', '4by3'), ('1by1', '1by1')], default='16by9', max_length=10)),
                ('candidates', models.ManyToManyField(to='election.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(blank=True, max_length=10)),
                ('is_kisa', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
                ('voted_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='election.Candidate')),
                ('voted_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='election.Election')),
            ],
        ),
    ]
