# Generated by Django 3.0 on 2020-11-07 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('manifesto', tinymce.models.HTMLField()),
                ('speech_url', models.CharField(blank=True, max_length=512, null=True)),
                ('kisa_history', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='election/img')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('intro_msg', tinymce.models.HTMLField()),
                ('instructions', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='election/img')),
                ('candidates', models.ManyToManyField(to='election.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_for_candidate', to='election.Candidate')),
                ('voted_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_for_election', to='election.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to=settings.AUTH_USER_MODEL)),
                ('votes', models.ManyToManyField(related_name='votes', to='election.ElectionVote')),
            ],
        ),
    ]
