# Generated by Django 3.0 on 2021-03-11 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voter',
            name='voted_candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='election.Candidate'),
        ),
        migrations.AddField(
            model_name='election',
            name='candidates',
            field=models.ManyToManyField(to='election.Candidate'),
        ),
    ]
