# Generated by Django 3.0 on 2020-11-07 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='votes',
        ),
        migrations.AddField(
            model_name='voter',
            name='voted_candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='election.Candidate'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ElectionVote',
        ),
    ]
