# Generated by Django 3.0 on 2021-12-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20211224_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='kisa_member_email_list',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
