# Generated by Django 3.0 on 2020-11-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_candidate_embed_video_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='yes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voter',
            name='vote_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
