# Generated by Django 3.0 on 2020-11-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20201126_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='debate_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='embed_video_ratio',
            field=models.CharField(choices=[('21by9', '21by9'), ('16by9', '16by9'), ('4by3', '4by3'), ('1by1', '1by1')], default='16by9', max_length=10),
        ),
        migrations.AddField(
            model_name='election',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
