# Generated by Django 3.0 on 2021-02-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_auto_20201127_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_kisa',
            field=models.BooleanField(default=False),
        ),
    ]
