# Generated by Django 3.0 on 2022-11-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_auto_20221119_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='kisa_in_debate_member_email_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='kisa_member_email_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
