# Generated by Django 4.2.11 on 2025-07-30 09:29

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sso", "0004_rename_student_status_korean_user_student_status_kor_and_more"),
        ("core", "0002_semester"),
        ("aboutus", "0002_alter_basecontent_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="KISADivisionContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "division",
                    models.IntegerField(
                        choices=[
                            (1, "Web Division"),
                            (2, "Finace Division"),
                            (3, "PPR Division"),
                            (4, "Events Division"),
                            (5, "Welfare Division"),
                            (6, "Secretary"),
                            (7, "Vice President"),
                            (8, "President"),
                        ],
                        db_index=True,
                    ),
                ),
                ("content", core.utils.DraftJSEditorField()),
            ],
        ),
        migrations.CreateModel(
            name="KISAMember",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("sns_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="KISARole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "division",
                    models.IntegerField(
                        choices=[
                            (1, "Web Division"),
                            (2, "Finace Division"),
                            (3, "PPR Division"),
                            (4, "Events Division"),
                            (5, "Welfare Division"),
                            (6, "Secretary"),
                            (7, "Vice President"),
                            (8, "President"),
                        ]
                    ),
                ),
                ("is_head", models.BooleanField()),
                ("members", models.ManyToManyField(to="aboutus.kisamember")),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.semester"
                    ),
                ),
            ],
            options={
                "unique_together": {("semester", "division", "is_head")},
            },
        ),
        migrations.RemoveField(
            model_name="constitutionpdf",
            name="basecontent_ptr",
        ),
        migrations.RemoveField(
            model_name="divisioncontent",
            name="basecontent_ptr",
        ),
        migrations.RemoveField(
            model_name="internalboardmember",
            name="basemember_ptr",
        ),
        migrations.RemoveField(
            model_name="internalboardmember",
            name="division",
        ),
        migrations.RemoveField(
            model_name="maincontent",
            name="basecontent_ptr",
        ),
        migrations.RemoveField(
            model_name="member",
            name="basemember_ptr",
        ),
        migrations.RemoveField(
            model_name="member",
            name="division",
        ),
        migrations.DeleteModel(
            name="BaseContent",
        ),
        migrations.DeleteModel(
            name="BaseMember",
        ),
        migrations.DeleteModel(
            name="ConstitutionPDF",
        ),
        migrations.DeleteModel(
            name="DivisionContent",
        ),
        migrations.DeleteModel(
            name="InternalBoardMember",
        ),
        migrations.DeleteModel(
            name="MainContent",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
