# Generated by Django 3.0 on 2021-10-23 04:42

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('batch', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DivisionDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('desc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='MainContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('desc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='InternalBoardMember',
            fields=[
                ('basemember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aboutus.BaseMember')),
                ('position', models.CharField(max_length=100, null=True)),
            ],
            bases=('aboutus.basemember',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('basemember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aboutus.BaseMember')),
                ('division', models.CharField(max_length=100, null=True)),
            ],
            bases=('aboutus.basemember',),
        ),
    ]
