# Generated by Django 3.0 on 2023-12-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalboardmember',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Division Head', 'Division Head'), ('Secretary', 'Secretary'), ('Deputy Secretary', 'Deputy Secretary')], max_length=100, null=True),
        ),
    ]
