# Generated by Django 3.0 on 2021-07-31 19:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('desc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('desc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Title',
            new_name='Members',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='title_text',
            new_name='title',
        ),
    ]
