# Generated by Django 3.0 on 2021-10-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecontent',
            options={'ordering': ['the_order']},
        ),
        migrations.RemoveField(
            model_name='basecontent',
            name='created',
        ),
        migrations.AddField(
            model_name='basecontent',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
