# Generated by Django 3.0 on 2021-10-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemember',
            name='batch',
        ),
        migrations.AddField(
            model_name='basemember',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
