# Generated by Django 3.0 on 2021-10-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20211023_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemember',
            name='created',
        ),
        migrations.RemoveField(
            model_name='internalboardmember',
            name='position',
        ),
        migrations.RemoveField(
            model_name='member',
            name='division',
        ),
        migrations.AddField(
            model_name='basemember',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basemember',
            name='semester',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='basemember',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
