# Generated by Django 3.0 on 2021-11-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_activemember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveMember',
        ),
    ]
