# Generated by Django 3.0 on 2021-11-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0006_auto_20211104_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalboardmember',
            options={},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.RemoveField(
            model_name='basemember',
            name='the_order',
        ),
    ]
