# Generated by Django 3.0 on 2021-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0007_auto_20211104_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalboardmember',
            options={'ordering': ['the_order']},
        ),
        migrations.AddField(
            model_name='internalboardmember',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
