# Generated by Django 3.0 on 2021-11-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0008_auto_20211104_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemember',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basemember',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
