# Generated by Django 3.0 on 2021-11-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0009_auto_20211105_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='basemember',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
