# Generated by Django 3.0 on 2022-02-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0010_auto_20211121_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemember',
            name='sns_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basemember',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Division Head', 'Division Head'), ('Secretary', 'Secretary'), ('Member', 'Member')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basemember',
            name='semester',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Fall', 'Fall')], max_length=10, null=True),
        ),
    ]
