# Generated by Django 3.0 on 2022-02-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0011_auto_20220208_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
