# Generated by Django 3.0 on 2022-02-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0014_auto_20220209_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', related_query_name='member', to='aboutus.Division'),
        ),
    ]
