# Generated by Django 3.0 on 2022-02-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0015_auto_20220209_1857'),
        ('aboutus', '0011_auto_20220209_1017'),
    ]

    operations = [
    ]
