# Generated by Django 3.0 on 2022-02-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0016_merge_20220217_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemember',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
