# Generated by Django 3.0 on 2022-03-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0017_auto_20220217_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemember',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Division Head', 'Division Head'), ('Secretary', 'Secretary'), ('Member', 'Member')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basemember',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basemember',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
