# Generated by Django 3.0 on 2022-03-21 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_divisionitem'),
        ('aboutus', '0018_auto_20220321_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionContent',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aboutus.BaseContent')),
                ('division_name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('aboutus.basecontent',),
        ),
        migrations.AlterModelOptions(
            name='basemember',
            options={'ordering': ['the_order']},
        ),
        migrations.AlterModelOptions(
            name='internalboardmember',
            options={},
        ),
        migrations.RemoveField(
            model_name='internalboardmember',
            name='the_order',
        ),
        migrations.AddField(
            model_name='basemember',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', related_query_name='member', to='aboutus.DivisionContent'),
        ),
        migrations.DeleteModel(
            name='Division',
        ),
    ]
