# Generated by Django 3.0 on 2022-03-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0020_auto_20220321_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemember',
            options={},
        ),
        migrations.AlterModelOptions(
            name='internalboardmember',
            options={'ordering': ['the_order']},
        ),
        migrations.RemoveField(
            model_name='basemember',
            name='the_order',
        ),
        migrations.AddField(
            model_name='internalboardmember',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
