# Generated by Django 3.0 on 2022-03-21 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0021_auto_20220321_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalboardmember',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aboutus.DivisionContent'),
        ),
        migrations.AlterField(
            model_name='member',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', related_query_name='member', to='aboutus.DivisionContent'),
        ),
    ]
