# Generated by Django 3.0 on 2022-03-21 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0022_auto_20220321_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstitutionPDF',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aboutus.BaseContent')),
            ],
            options={
                'abstract': False,
            },
            bases=('aboutus.basecontent',),
        ),
    ]
