# Generated by Django 3.0 on 2022-03-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0023_constitutionpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='constitutionpdf',
            name='constitution_file',
            field=models.FileField(null=True, upload_to='constitution'),
        ),
    ]
