# Generated by Django 3.0 on 2021-01-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210119_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='sub_categories',
            field=models.ManyToManyField(null=True, related_name='_postcategory_sub_categories_+', to='blog.PostCategory'),
        ),
    ]
