# Generated by Django 3.0 on 2022-01-18 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('important_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkcategory',
            name='title_category',
            field=models.CharField(blank=True, max_length=200, unique=True, validators=[django.core.validators.RegexValidator('[^\\w\\-]', inverse_match=True, message='Spaces and punctuation (except "-" and "_") are not allowed.')]),
        ),
    ]
