# Generated by Django 4.2.7 on 2023-11-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("important_links", "0003_auto_20220312_2229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="linkcategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
