# Generated by Django 3.0 on 2021-07-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('alt', models.TextField()),
                ('slug', models.SlugField()),
                ('file', models.ImageField(upload_to='images')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MultimediaTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('file', models.FileField(upload_to='videos')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('date', models.DateField()),
                ('images', models.ManyToManyField(to='multimedia.Image')),
                ('tag', models.ManyToManyField(to='multimedia.MultimediaTags')),
                ('videos', models.ManyToManyField(to='multimedia.Video')),
            ],
        ),
    ]
