# Generated by Django 3.0 on 2021-09-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0003_auto_20210918_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimedia',
            old_name='tag',
            new_name='tags',
        ),
    ]
