# Generated by Django 3.0 on 2022-11-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0006_auto_20221104_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embed_video_ratio',
            field=models.CharField(choices=[('21by9', '21by9'), ('16by9', '16by9'), ('4by3', '4by3'), ('1by1', '1by1')], default='16by9', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='multiple_images',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
