# Generated by Django 3.0 on 2022-11-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0011_auto_20221106_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
