# Generated by Django 4.2.11 on 2025-07-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("multimedia", "0013_alter_image_id_alter_multimedia_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultimediaImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        help_text="Enables screen readers to read the information about the image",
                        max_length=100,
                    ),
                ),
                ("file", models.ImageField(upload_to="images")),
                ("date", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="multimedia",
            name="carousels",
        ),
        migrations.RemoveField(
            model_name="multimedia",
            name="date",
        ),
        migrations.RemoveField(
            model_name="multimedia",
            name="multiple_images",
        ),
        migrations.RemoveField(
            model_name="multimedia",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="multimedia",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="multimedia",
            name="videos",
        ),
        migrations.RemoveField(
            model_name="multimedia",
            name="visible",
        ),
        migrations.AddField(
            model_name="multimedia",
            name="description",
            field=models.TextField(default="No Description"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="MultimediaTag",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
        migrations.AlterField(
            model_name="multimedia",
            name="images",
            field=models.ManyToManyField(blank=True, to="multimedia.multimediaimage"),
        ),
    ]
