# Generated by Django 3.0 on 2021-03-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisa_voice_link', models.URLField(blank=True)),
                ('kisa_books_link', models.URLField(blank=True)),
                ('internships_link', models.URLField(blank=True)),
                ('kaist_ara_link', models.URLField(blank=True)),
            ],
        ),
    ]
