# Generated by Django 3.0 on 2020-09-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='fb_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='insta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='kisa_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='footer',
            name='yt_link',
            field=models.URLField(blank=True),
        ),
    ]
