# Generated by Django 3.0 on 2020-11-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200912_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmptyQueryset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
