# Generated by Django 3.0 on 2022-11-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221002_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='kisa_room_reservation_link',
            field=models.URLField(blank=True),
        ),
    ]
