# Generated by Django 3.0 on 2020-11-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emptyqueryset'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=255, unique=True)),
                ('class_name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
