# Generated by Django 3.0 on 2021-08-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_navbar_course_resources_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseResources',
        ),
        migrations.DeleteModel(
            name='CourseUrl',
        ),
    ]
