# Generated by Django 3.0 on 2022-02-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210829_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
