# Generated by Django 3.0 on 2021-11-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0009_auto_20211105_0003'),
        ('core', '0004_auto_20210829_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=50, null=True)),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutus.DivisionDescription')),
            ],
            options={
                'ordering': ['the_order'],
            },
        ),
    ]
