# Generated by Django 3.0 on 2022-03-21 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_divisionitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DivisionItem',
        ),
    ]
