# Generated by Django 3.0 on 2022-03-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_divisionitem'),
        ('core', '0005_auto_20220225_2304'),
    ]

    operations = [
    ]
