# Generated by Django 3.0 on 2022-01-21 09:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kaist Club', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('slogan', models.CharField(default='Make KAIST a fun and intersting place to study', max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('catagory', models.CharField(choices=[('Academic', 'Academic'), ('Sports', 'Sports'), ('Music', 'Music'), ('Arts', 'Arts'), ('Life and Culture', 'Life and Culture'), ('Religion and Society', 'Religion and Society')], default='Academic', max_length=50)),
                ('Information', tinymce.models.HTMLField()),
            ],
        ),
    ]
