# Generated by Django 3.0 on 2022-02-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(default='Club name', max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='slogan',
            field=models.CharField(default='Make KAIST a fun and interesting place to study', max_length=500),
        ),
    ]
