# Generated by Django 3.0 on 2022-02-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20220220_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='Information',
            new_name='information',
        ),
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, editable=False, max_length=100),
        ),
    ]
