# Generated by Django 3.0 on 2022-02-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20220220_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
