# Generated by Django 3.0 on 2022-02-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20220220_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='clubs.Catagory'),
        ),
    ]
