# Generated by Django 3.0 on 2022-02-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20220226_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='catagory_title',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
