# Generated by Django 3.0 on 2022-02-27 10:42

from django.db import migrations, models
import django.db.models.deletion
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20220226_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='catagory_title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='clubs.Catagory'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
