# Generated by Django 4.2.11 on 2024-05-04 11:33

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):
    dependencies = [
        ("election", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="election",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.latest,
                on_delete=django.db.models.deletion.CASCADE,
                to="election.election",
            ),
        ),
        migrations.AlterField(
            model_name="votingexceptiontoken",
            name="election",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.latest,
                on_delete=django.db.models.deletion.CASCADE,
                to="election.election",
            ),
        ),
    ]
