# Generated by Django 4.2.11 on 2025-07-30 09:29

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):
    dependencies = [
        ("election", "0002_alter_candidate_election_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="election",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.latest,
                on_delete=django.db.models.deletion.CASCADE,
                to="election.election",
            ),
        ),
        migrations.AlterField(
            model_name="election",
            name="instructions",
            field=core.utils.DraftJSEditorField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="election",
            name="intro_msg",
            field=core.utils.DraftJSEditorField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="vote",
            name="candidate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="election.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="votingexceptiontoken",
            name="election",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.latest,
                on_delete=django.db.models.deletion.CASCADE,
                to="election.election",
            ),
        ),
    ]
