# Generated by Django 3.0 on 2021-01-19 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='parent_category',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.PostCategory'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='sub_categories',
            field=models.ManyToManyField(related_name='_postcategory_sub_categories_+', to='blog.PostCategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
