# Generated by Django 3.0 on 2021-01-19 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210119_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.PostCategory'),
        ),
    ]
