# Generated by Django 3.0 on 2021-01-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210119_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='_postcategory_sub_categories_+', to='blog.PostCategory'),
        ),
    ]
