# Generated by Django 3.0 on 2021-01-19 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210119_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='sub_categories',
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.PostCategory'),
        ),
    ]
