# Generated by Django 3.0 on 2021-01-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_descr_truncate_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/img'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_height',
            field=models.PositiveSmallIntegerField(blank=True, default=260),
        ),
        migrations.AddField(
            model_name='post',
            name='image_width',
            field=models.PositiveSmallIntegerField(blank=True, default=260),
        ),
    ]
