# Generated by Django 3.0 on 2021-07-03 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210513_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttag',
            name='tag_name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('\\w+', 'Spaces And Punctuation Are Not Allowed.')]),
        ),
    ]
