# Generated by Django 3.0 on 2021-07-11 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210711_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttag',
            name='tag_name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('[^\\w\\-]', inverse_match=True, message='Spaces And Punctuation Are Not Allowed.')]),
        ),
    ]
