# Generated by Django 3.0 on 2021-10-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210502_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='no_prize',
            field=models.BooleanField(default=False, verbose_name='Event has no prize'),
        ),
        migrations.AddField(
            model_name='event',
            name='prize1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='prize2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='prize3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
