# Generated by Django 4.2.5 on 2023-09-24 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavBarEntry',
            fields=[
                ('index', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NavDropdownData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NavLinkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('style', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NavDropDownEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, unique=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.navlinkdata')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.navdropdowndata')),
            ],
        ),
        migrations.AddField(
            model_name='navdropdowndata',
            name='entries',
            field=models.ManyToManyField(through='misc.NavDropDownEntry', to='misc.navlinkdata'),
        ),
        migrations.CreateModel(
            name='NavBarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.navlinkdata')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.navbarentry')),
            ],
        ),
        migrations.CreateModel(
            name='NavBarDropdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.navdropdowndata')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.navbarentry')),
            ],
        ),
    ]
