# Generated by Django 4.2.5 on 2023-09-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navdropdowndata',
            name='entries',
            field=models.ManyToManyField(through='misc.NavDropdownEntry', to='misc.navlinkdata'),
        ),
    ]
