# Generated by Django 4.2.5 on 2023-09-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_alter_navdropdowndata_entries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navdropdownentry',
            old_name='order',
            new_name='index',
        ),
    ]
