# Generated by Django 4.2.11 on 2025-07-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "season",
                    models.IntegerField(
                        choices=[
                            (0, "Spring"),
                            (1, "Summer"),
                            (2, "Fall"),
                            (3, "Winter"),
                        ]
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-season"],
            },
        ),
    ]
