"""
Django settings for web project
=================================

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/

See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

Style guide
------------

Secure options should be the default settings, and deployment failure is preferred over unsecure settings.
E.g. ``dict['key']`` Vs. ``dict.get('key', '')``

Accessing the environment variables should be done only within this file.

The environment variables in-use
- ALLOWED_HOSTS
- API_ROOT
- CORS_ALLOW_CREDENTIALS
- CORS_ALLOWED_ORIGINS
- DB_NAME
- DB_USER
- DB_PASSWORD
- DB_HOST
- DB_PORT
- DOTENV_FILE
- DEBUG
- KSSO_CLIENT_SECRET
- SECRET_KEY
- SMTP_SERVER
- SMTP_USERNAME
- SMTP_PASSWORD
"""


import os, urllib.parse
from pathlib import Path
from dotenv import load_dotenv
from django.conf.global_settings import DATETIME_INPUT_FORMATS


# Try to load dotenv file
if 'DOTENV_FILE' in os.environ:
    load_dotenv(os.environ['DOTENV_FILE'])


# Project top-level
BASE_DIR = Path(__file__).parent.parent.absolute() # Build paths inside the project like this: BASE_DIR.joinpath(*pathsegments)
API_ROOT = os.environ['API_ROOT']

# Django top-level
INSTALLED_APPS = [
    'django.contrib.admin.apps.SimpleAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    'rest_framework',

    ## ---- Third Party Libraries ---- ##
    # 'maintenance_mode',  # PyPi django-maintenance-mode (this needs to be before any custom apps)
    # 'compressor',  # PyPi django-compressor
    # 'tinymce',  # PyPi django-richtextfield
    # 'crispy_forms',  # PyPi django-crispy-forms
    # 'docs',  # PyPi django-docs
    # 'phone_field',  # PyPi django-phone-field
    # 'adminsortable',
    "django_pagination_bootstrap", #pagination for multimedia page,
    'django_draftjs',

    'core',
    'sso',
    'events',
    'election',
    'aboutus',
    'multimedia',
    'blog',
    'faq',
    'important_links',
    'url_shortener',
    'alumni',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_pagination_bootstrap.middleware.PaginationMiddleware", #django_pagination_bootstrap middleware
    'maintenance_mode.middleware.MaintenanceModeMiddleware',  # PyPi django-maintenance-mode (This needs to be the last middleware)
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR.joinpath('admin', 'templates'),
            BASE_DIR,
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # required by django-3-jet
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.static',
                'django.contrib.messages.context_processors.messages',
                'maintenance_mode.context_processors.maintenance_mode',  # PyPi django-maintenance-mode
                "django.template.context_processors.request", # django_pagination_bootstrap context provider
            ],
        },
    },
]
WSGI_APPLICATION = 'web.wsgi.application'
ROOT_URLCONF = 'web.urls'
AUTH_USER_MODEL = 'sso.User'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
DATABASES = {
    'default' : {
        'ENGINE'    : 'django.db.backends.postgresql',
        'NAME'      : os.environ['DB_NAME'],
        'USER'      : os.environ['DB_USER'],
        'PASSWORD'  : os.environ['DB_PASSWORD'],
        'HOST'      : os.environ['DB_HOST'],
        'PORT'      : os.environ['DB_PORT']
    }
}
CONN_MAX_AGE = None
DEFAULT_AUTO_FIELD  = 'django.db.models.BigAutoField'


# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.utils.StrictCSRFSessionAuthentication',
    ],

    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'core.throttling.UserRateThrottle',
    ],

    'DEFAULT_THROTTLE_RATES': {
        'anon': '200/day',
        'user': '1000/day',
        'email_otp': '10/day',
    },

    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
}


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
USE_I18N = True
USE_L10N = False
TIME_ZONE = 'Asia/Seoul'
USE_TZ = True
DATETIME_INPUT_FORMATS += [
    '%Y-%m-%d %I:%M %p',  # 2020-01-20 06:30 PM
    '%Y/%m/%d',  # 2020/01/20
    '%Y-%m-%d %H:%M',  # 2020-01-20 13:30
    '%Y-%m-%d',  # 2020-01-20
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_URL = API_ROOT + 'static/'
STATIC_ROOT = BASE_DIR.parent.parent.joinpath('build', *urllib.parse.urlparse(API_ROOT).path.split('/')[1:-1], 'static')
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]
MEDIA_URL = API_ROOT + 'media/'
MEDIA_ROOT = BASE_DIR.parent.joinpath('media')


# Mail service
DEFAULT_FROM_EMAIL = 'kisa@kaist.ac.kr'
EMAIL_HOST = os.environ['SMTP_SERVER']
EMAIL_PORT = '587'
EMAIL_HOST_USER = os.environ['SMTP_USERNAME']
EMAIL_HOST_PASSWORD = os.environ['SMTP_PASSWORD']


# HTTP Security
ALLOWED_HOSTS = os.environ['ALLOWED_HOSTS'].split(',')
CORS_ALLOWED_ORIGINS = os.environ['CORS_ALLOWED_ORIGINS'].split(',')
CORS_ALLOW_CREDENTIALS = bool(int(os.environ['CORS_ALLOW_CREDENTIALS']))
X_FRAME_OPTIONS = 'DENY'


# Application-level Security
SECRET_KEY = os.environ['SECRET_KEY'] # used for cryptographic sigining
DEBUG = bool(int(os.environ.get('DEBUG', 0))) # SECURITY WARNING: don't run with debug turned on in production!
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
EMAIL_USE_TLS = True


## Third-party

# django-compressor
COMPRESS_PRECOMPILERS = [
    ('text/x-scss', 'django_libsass.SassCompiler'),
]
COMPRESS_ENABLED = True


# django-docs
DOCS_ROOT = BASE_DIR.joinpath('docs', 'build', 'html')
DOCS_ACCESS = 'staff'


## Application-specific

# sso
KSSO_CLIENT_ID = 'kaist-kisa'
KSSO_CLIENT_SECRET = os.environ['KSSO_CLIENT_SECRET']
KSSO_REDIRECT_URI = 'https://kisa.kaist.ac.kr/api/sso/login'
KSSO_AUTH_REQUEST_URI = 'https://sso.kaist.ac.kr/auth/user/single/login/authorize'
KSSO_INFO_REQUEST_URI = 'https://sso.kaist.ac.kr/auth/api/single/auth'


# url_shortener
URL_SHORTENER_PREFIX    = 'short-link'
