# Generated by Django 4.2.7 on 2023-11-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_navbar_kisa_room_reservation_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="fb_link",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="insta_link",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="kisa_text",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="location",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="phnum_eng",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="phnum_kor",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="yt_link",
        ),
        migrations.RemoveField(
            model_name="navbar",
            name="course_resources_link",
        ),
        migrations.RemoveField(
            model_name="navbar",
            name="internships_link",
        ),
        migrations.RemoveField(
            model_name="navbar",
            name="kaist_ara_link",
        ),
        migrations.RemoveField(
            model_name="navbar",
            name="kisa_books_link",
        ),
        migrations.RemoveField(
            model_name="navbar",
            name="kisa_room_reservation_link",
        ),
        migrations.RemoveField(
            model_name="navbar",
            name="kisa_voice_link",
        ),
        migrations.AddField(
            model_name="footer",
            name="json",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="navbar",
            name="json",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="emptyqueryset",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="footer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="navbar",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
