# Generated by Django 4.2.10 on 2024-02-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="post",
            name="new_content",
            field=models.JSONField(default=dict),
        ),
    ]
