# Generated by Django 4.2.11 on 2025-07-30 09:29

import core.utils
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_description_post_new_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="new_content",
            field=core.utils.DraftJSEditorField(default=dict),
        ),
    ]
