# Generated by Django 4.2.11 on 2024-05-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sso", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="kisa_division",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "Web Division"),
                    (2, "Finace Division"),
                    (3, "PPR Division"),
                    (4, "Events Division"),
                    (5, "Welfare Division"),
                    (6, "Secretary"),
                    (7, "Vice President"),
                    (8, "President"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="totp_device",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="sso.totpdevice"
            ),
        ),
    ]
