# Generated by Django 4.2.11 on 2024-05-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sso", "0002_alter_user_kisa_division_alter_user_totp_device"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="totpdevice",
            name="next_delay_sec",
        ),
        migrations.RemoveField(
            model_name="totpdevice",
            name="on_cooldown",
        ),
        migrations.AddField(
            model_name="totpdevice",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="totpdevice",
            name="num_failed_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
