# Generated by Django 4.2.11 on 2025-01-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sso", "0003_remove_totpdevice_next_delay_sec_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="student_status_korean",
            new_name="student_status_kor",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bachelors_department_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bachelors_department_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="degree_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="degree_name_english",
        ),
        migrations.RemoveField(
            model_name="user",
            name="degree_name_korean",
        ),
        migrations.RemoveField(
            model_name="user",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="user",
            name="external_email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="kaist_email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="korean_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="user",
            name="sex",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student_admission_datetime",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student_category_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student_enrollment_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student_graduation_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student_status_english",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student_type_class",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student_type_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="title_english",
        ),
        migrations.AddField(
            model_name="user",
            name="business_phone",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_department_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_department_name_english",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_department_name_korean",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_status_kor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="english_name",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="organization_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="campus",
            field=models.CharField(default="D", max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="user",
            name="kaist_uid",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sso_id",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="student_department_name_english",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="student_department_name_korean",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
